# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[(b'nombre', b'Nombre'), (b'telefono', b'Telefono'), (b'email', b'Email'), (b'extra', b'Extra')], max_length=10)),
            ],
        ),
    ]
