# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serie',
            new_name='Persona',
        ),
    ]
