# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0002_auto_20170418_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='category',
            field=models.CharField(choices=[(b'noob', b'Noob'), (b'principiant', b'Principiant'), (b'moderate', b'Moderate'), (b'expert', b'Expert')], max_length=10),
        ),
    ]
